[PM2127H14417640]
dpi_x = 763
dpi_y = 763
poll_rate = 1000
logo_active = True
logo_brightness = 75
logo_effect = breathDual
logo_colors = 136 192 208 136 222 233 0 0 255
logo_speed = 4
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 55
scroll_effect = reactive
scroll_colors = 136 192 208 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

