# https://wiki.hyprland.org/Configuring/Variables/#gestures

gestures {
  gesture = 3, horizontal, scale: 1.0, workspace
  gesture = 3, down,   scale: 1.7, dispatcher, movefocus, u
  gesture = 3, up,   scale: 1.7, dispatcher, movefocus, d
}
