opengl {
  nvidia_anti_flicker = true
}

misc {
  animate_mouse_windowdragging = true
  animate_manual_resizes = true
  # layers_hog_keyboard_focus = true
  enable_swallow = true
  swallow_regex = '.*'
}

ecosystem {
  enforce_permissions = true

  permission = /usr/bin/grim, screencopy, allow
  permission = /usr/bin/flameshot, screencopy, allow
  permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
}
