$ipc = qs -c noctalia-shell ipc call

$terminal = kitty 
$secondaryTerminal = foot

$browser = firefox

$fileManager = dolphin

$readingApp = okular

$menu = $ipc launcher toggle

$storePastedText = wl-paste --type text --watch cliphist store
$storePastedImage = wl-paste --type image --watch cliphist store
$clipboardMenu = $ipc launcher clipboard

$bar = qs -c noctalia-shell --no-duplicate

$toggleBar = $ipc bar toggle
$toggleNotification = $ipc notifications toggleHistory
$toggleDashboard = $ipc controlCenter toggle
$togglePowerMenu = $ipc sessionMenu toggle
$toggleSettings  = $ipc settings toggle

$emojiPicker = $ipc launcher emoji
