# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
  name = ignore-maximize-requests
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = fix-dragging-issues
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = open-btop-always-in-4th-workspace
  workspace = 4 silent
  match:title = btop
}

windowrule {
  name = open-qemu-always-in-3rd workspace
  workspace = 3 silent
  match:class = qemu
}

windowrule {
  name = open-mame-always-in-3rd workspace
  workspace = 3 silent
  match:class = mame
}

windowrule {
  name = make-webapps-opaque
  opaque = on
  match:class = ^WebApp.*
}

windowrule {
  name = make-firefox-opaque
  opaque = on
  match:class = firefox
}

windowrule {
  name = make-okular-opaque
  opaque = on
  match:class = org.kde.okular
}
