# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule {
  name = ignore-maximize-requests
  suppress_event = maximize
  match:class = .*
}

windowrule {
  name = fix-dragging-issues
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = open-in-2nd-workspace
  
  match:class = ^WebApp.*|firefox

  workspace = 2 silent
}

windowrule {
  name = open-in-3rd-workspace

  match:class = qemu|mame

  workspace = 3 silent
}

windowrule {
  name = open-in-4th-workspace

  match:title = btop

  workspace = 4 silent
}

windowrule {
  name = opaque-apps

  match:class = ^WebApp.*|mame|qemu|kitty

  opaque = on 
}
