- ansible.builtin.import_tasks: packages.yml
- ansible.builtin.import_tasks: services.yml
- ansible.builtin.import_tasks: stow.yml
- ansible.builtin.import_tasks: users.yml
- ansible.builtin.import_tasks: misc.yml
