- name: Set timezone
  tags: misc
  ansible.builtin.timezone:
    name: Etc/GMT-2

- name: Ensure primary locale is generated
  tags: misc,locale
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set default system locale
  tags: misc,locale
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8
  changed_when: false

- name: Set hostname
  tags: misc
  ansible.builtin.hostname:
    name: "thelaptop"

- name: Ensure wallpaper directory exists
  tags: misc
  ansible.builtin.file:
    path: /usr/share/wallpapers
    state: directory
    mode: "0755"
  become: true

- name: Symlink wallpaper directories
  tags: misc
  ansible.builtin.file:
    src: "/home/{{ user }}/dotfiles/ansible/roles/thelaptop/files/wallpapers/{{ item }}"
    dest: "/usr/share/wallpapers/{{ item }}"
    state: link
    force: true
  loop:
    - Nord
    - AltNord
    - Favorites
    - ArchPapers
  become: true

- name: Install zinit
  tags: misc
  ansible.builtin.git:
    repo: "https://github.com/zdharma-continuum/zinit.git"
    dest: "/home/{{ user }}/.local/share/zinit"
    depth: 1
  become: true
  become_user: "{{ user }}"
  environment:
    GIT_CONFIG_GLOBAL: "/dev/null"
    GIT_CONFIG_SYSTEM: "/dev/null"

- name: Require password for 'wheel' group when doing sudo
  tags: thelaptop,users
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel ALL="
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
