- name: Enable services
  tags: services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  loop:
    - greetd.service

    - kmsconvt@tty2.service
    - kmsconvt@tty3.service
    - kmsconvt@tty4.service
    - kmsconvt@tty5.service
    - getty@tty6.service

    - NetworkManager.service
    - systemd-resolved.service
    - bluetooth.service
    - chronyd.service

    - supergfxd.service
    - switcheroo-control.service
    - tlp.service

    - docker.socket
    - libvirtd.socket

    - fstrim.timer
    - reflector.timer
  become: true

- name: Let NetworkManager manage iwd
  tags: services
  ansible.builtin.systemd_service:
    name: iwd.service
    enabled: false
  become: true
