- name: Ensure 'm0st4fa' user exists and is configured
  tags: thelaptop,users
  ansible.builtin.user:
    name: m0st4fa
    state: present
    shell: /bin/zsh
    groups: wireshark, docker, libvirt, input, wheel, tss, android-sdk, openrazer
    append: yes

- name: Allow 'wheel' group to use sudo
  tags: thelaptop,users
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel ALL="
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
