### General
debug

### Graphics
drm
hwaccel
render-engine=gltex
use-original-mode

### Fonts
font-engine=pango
font-size=16
font-name=FiraCode Nerd Font
font-dpi=96

### Input Options
## Keyboard
xkb-model=pc105
xkb-layout=us
xkb-options=ctrl:nocaps
xkb-repeat-delay=200
xkb-repeat-rate=50

## Keyboard Shortcuts

## Enable mouse
mouse

### Power Management
dpms-timeout=600

### Terminal options
term=xterm-256color
reset-env
backspace-delete
sb-size=10000

# ------------- Nord Palette -----------------
palette=custom

palette-black=46,52,64
palette-red=191,97,106
palette-green=163,190,140
palette-yellow=235,203,139
palette-blue=129,161,193
palette-magenta=180,142,173
palette-cyan=136,192,208
palette-light-grey=216,222,233

palette-dark-grey=76,86,106
palette-light-red=191,97,106
palette-light-green=163,190,140
palette-light-yellow=235,203,139
palette-light-blue=129,161,193
palette-light-magenta=180,142,173
palette-light-cyan=136,192,208
palette-white=236,239,244

palette-foreground=216,222,233
palette-background=46,52,64
