packages_appearance:
  - qt6ct
  - kvantum
  - nwg-look
  - plymouth
  - papirus-icon-theme
  - colloid-nord-gtk-theme-git
  - figlet
  - go-rainbow-git
  - ttf-recursive-nerd
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-meslo-nerd
  - ttf-fira-code
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd
  - terminus-font
  - ttf-dejavu

