packages_communication:
  - firefox
  - discord
  - telegram-desktop-bin # Statically compiled; the dynamic package has caused problems.
  - neomutt

package_feature_sets_communication:
  neomutt:
    - w3m
    - urlscan
