core:
  - base
  - base-devel
  - linux
  - linux-firmware
  - linux-headers
  - networkmanager
  - grub
  - efibootmgr
  - git
  - stow
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zoxide
  - eza
  - fd
  - fzf
  - bat
  - btop
  - htop
  - neovim
  - jq
  - rsync
  - wget
  - zip
  - unzip
  - tlp
