core:
  - base
  - base-devel
  - cmake
  - cmake-extras
  - linux
  - linux-firmware
  - linux-headers
  - grub
  - efibootmgr
  - intel-ucode
  - ntfsprogs
  - xfsprogs

  - git
  - stow

  - neovim
  - libvirt
  - openai-codex
  - antigravity-cli
  - typescript

  - kmscon
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zoxide
  - eza
  - fd
  - fzf
  - bat
  - btop
  - htop
  - yazi
  - jq
  - rsync
  - wget
  - zip
  - unzip
  - ripgrep
  - libqalculate
  - ncdu

  - networkmanager
  - iwd
  - chrony
  - tlp
  - reflector
