desktop:
  - hyprland
  - hypridle
  - hyprlock
  - hyprsunset
  - hyprpolkitagent
  - nwg-look
  - wl-clipboard
  - grim
  - slurp
  - kitty
  - wezterm
  - foot
  - firefox
  - discord
  - obsidian
  - pavucontrol
  - bluez-utils
  - greetd-tuigreet
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-wlr
  - qt6ct
  - kvantum
  - waydroid
  - polychromatic
  - gimp
