desktop:
  - hyprland
  - hypridle
  - hyprlock
  - hyprsunset
  - hyprpolkitagent
  - greetd-tuigreet
  - noctalia

  - wl-clipboard
  - cliphist
  - grim
  - slurp
  - pavucontrol
  - switcheroo-control
  - supergfxctl
  - bluez
  - bluez-utils
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-wlr
  - electron32-bin # Many depend on it; downloads -git by default, so this forces -bin
  - tesseract-data-eng
  - tesseract-data-ara

  - kitty
  - wezterm
  - foot

  - waydroid
  - gimp
  - firefox
  - discord
  - obsidian
  - mpd
  - polychromatic
  - zathura
  - zathura-pdf-mupdf
