packages_desktop_session:
  - hyprland
  - hypridle
  - hyprlock
  - hyprsunset
  - hyprpolkitagent
  - greetd-tuigreet
  - noctalia

  - wl-clipboard
  - cliphist
  - libnotify

  - grim
  - slurp
  - satty
  - wf-recorder

  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - gnome-keyring
