packages_development:
  - base-devel
  - cmake
  - cmake-extras
  - git

  - neovim
  - neovide

  - openai-codex
  - antigravity-cli

  # Languages & Frameworks
  - typescript
  - android-cli
  - jdk17-openjdk
  - fvm
  - clang
  - go

  # Libraries
  - cglm
  - glm
