fonts_and_themes:
  - qt6ct
  - kvantum
  - nwg-look

  - ttf-recursive-nerd
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ttf-meslo-nerd
  - ttf-fira-code
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd
  - terminus-font

  - papirus-icon-theme
  - colloid-nord-gtk-theme-git
  - figlet
  - go-rainbow-git
  - plymouth-theme-owl-git
