packages_terminal:
  - kitty
  - wezterm
  - foot

  - zsh
  - bash-completion

  - zoxide
  - eza
  - fd
  - fzf
  - bat
  - btop
  - htop
  - yazi
  - jq
  - rsync
  - wget
  - zip
  - unzip
  - ripgrep
  - libqalculate
  - ncdu
  - yt-dlp
  - taskwarrior
  - tldr

package_feature_sets_terminal:
  zsh:
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  yt_dlp:
    - python-brotli
    - python-xattr
    - python-secretstorage
    - python-pycryptodomex
    - python-websockets
    - python-curl_cffi
    - python-mutagen
    - atomicparsley
  yazi:
    - perl-image-exiftool
    - perl-archive-zip
    - perl-io-compress-brotli
