packages_terminal:
  - kitty
  - wezterm
  - foot

  - zsh

  - zip
  - unzip
  - 7zip

  - libqalculate
  - taskwarrior
  - timewarrior

  - zoxide
  - eza
  - fd
  - yazi

  - bat
  - bat-extras
  - tree

  - man-db
  - tldr

  - btop
  - htop

  - jq
  - ripgrep
  - fzf
  - ncdu
  - pet-bin

  - rsync
  - wget
  - yt-dlp

package_feature_sets_terminal:
  zsh:
    - bash-completion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-completions
    - zsh-lovers
  yt_dlp:
    - python-brotli
    - python-xattr
    - python-secretstorage
    - python-pycryptodomex
    - python-websockets
    - python-curl_cffi
    - python-mutagen
    - atomicparsley
  yazi:
    - perl-image-exiftool
    - perl-archive-zip
    - perl-io-compress-brotli
    - mediainfo
